### PR TITLE
Check if marketplace request is on pending state before delete.

### PR DESCRIPTION
**Pull request by pontovinte**
Status can be [ pending, provisioned, rejected ]
    if rejected or provisioned, we skip the delete, if pending, we do the delete as you already implemented it.

### CODE REVIEW

**Comment by rjouhann** [comment]
Could we modify the message this way for DELETE and UPDATE operations so the user knows if the request has been accepted or rejected.

If state is `provisioned`: => not end with error state in terraform 
```
╷
│ Warning: The Z side has approved the request and provisioned the connection. Please import the new resource created to manage it with Terraform and update your Terraform configuration.
│ 
```

If state is `rejected`: => end with error state in terraform 
```
╷
│ Error: The Z side has rejected the request.
│ 
```

**Review by rjouhann — CHANGES_REQUESTED** [review]
Could we modify the message this way for DELETE and UPDATE operations so the user knows if the request has been accepted or rejected.

If state is `provisioned`: => not end with error state in terraform 
```
╷
│ Warning: The Z side has approved the request and provisioned the connection. Please import the new resource created to manage it with Terraform and update your Terraform configuration.
│ 
```

If state is `rejected`: => end with error state in terraform 
```
╷
│ Error: The Z side has rejected the request.
│ 
```

**Comment by pontovinte** [comment]
@rjouhann, in case of `PROVISIONED` the TF Plugin can tag it as DELETED?

**Comment by rjouhann** [comment]
1. I can see the error when the connection has been `rejected`
2. However, I can't see the message when connection has been `provisioned`
3. Also, it would be great to check the status in the update operation to find out if the connection request has been rejected or provisioned, same behavior than the delete (if rejected = error, if provisioned = warning)

```
Changes to Outputs:
  - packetfabric_cs_aws_hosted_marketplace_connection = {
      - account_uuid   = "24a0aef3-2784-48dc-9a8e-52d44d6da646"
      - aws_account_id = "687236962849"
      - description    = "demo-holy-shrew"
      - id             = "e4d8f2fb-aa48-4e59-9e95-854335c6d53a"
      - market         = "HOU"
      - pop            = "SFO6"
      - routing_id     = "PD-WUY-9VB0"
      - speed          = "50Mbps"
      - timeouts       = null
      - zone           = "A"
    } -> null
packetfabric_cs_aws_hosted_marketplace_connection.cs_conn1_marketplace: Destroying... [id=e4d8f2fb-aa48-4e59-9e95-854335c6d53a]
packetfabric_cs_aws_hosted_marketplace_connection.cs_conn1_marketplace: Destruction complete after 0s
random_pet.name: Destroying... [id=holy-shrew]
random_pet.name: Destruction complete after 0s
╷
│ Warning: AWS Hosted marketplace delete result
│ 
│ 
Destroy complete! Resources: 2 destroyed.
```

**Review by rjouhann — APPROVED** [review]

**Pull request merged**
