### PR TITLE
Change resources and datasources file name

### PR DESCRIPTION
**Pull request by pontovinte**
Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

### CODE REVIEW

**Review by medzin — CHANGES_REQUESTED** [review]
Well, it doesn't solve the problem. I expected to rename the resource names I use in Terraform code so, for example, `cloud_router` will become `packetfabric_cloud_router`. I updated the issue as well, to be more precise. Sorry for the imprecise description.

**Comment by pontovinte** [comment]
No problem @medzin, thanks for explaining it better.
Let me take a look and propose a new patch.

**Comment by pontovinte** [comment]
Hi @medzin, I think I got it right at this time. Please let me know what do you think.
Thanks again for clarifying it.

**Comment by medzin** [comment]
@pontovinte looks great! Will you update docs in the same PR on another one?

**Comment by pontovinte** [comment]
Hi @medzin thanks for your feedback! Yes, we'll provide the doc updates on different PRs.

**Review by medzin — APPROVED** [review]

**Comment by elXaptation** [comment]
Docs updates coming in separate PR.

**Pull request merged**
