### PR TITLE
#203: Datasource packetfabric_locations_pop_zones

### LINKED ISSUE #203: data source packetfabric_locations_pop_zone
List all PacketFabric pop in a zone

data source `packetfabric_locations_pop_zone`
GET [/v2/locations/{pop}/zones](https://docs.packetfabric.com/api/v2/swagger/#/Locations/get_location_zone_availability)
User Input: PoP name (string)

Checklist:
- [ ] tested locally
- [ ] added/updated acceptance tests
- [ ] add examples (in example folder)
- [ ] generate docs

### PR DESCRIPTION
**Pull request by pontovinte**
Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

## Description

DataSource packetfabric_locations_pop_zones

Closes #203 

## Checklist

- [x] tested locally
- [x] added/updated acceptance tests
- [x] add examples (in example folder)
- [x] generate docs

### CODE REVIEW

**Comment by medzin** [comment]
Working on acceptance test.

**Comment by medzin** [comment]
Acceptance test added.

**Review by elXaptation — APPROVED** [review]

**Review by rjouhann — APPROVED** [review]

**Comment by rjouhann** [comment]
@elXaptation could you add the examples/docs and move the PR to Documentation for @caitlinwheeless to review?

**Review by elXaptation — APPROVED** [review]

**Comment by elXaptation** [comment]
Example and Docs ready for review.. @caitlinwheeless @rjouhann

**Review by rjouhann — APPROVED** [review]

**Pull request merged**
