### PR TITLE
254: Implement feature packetfabric_quick_connect_reject_request.

### LINKED ISSUE #254: resource packetfabric_quick_connect_reject_request
**resource** `packetfabric_quick_connect_reject_request`

POST [/v2/services/cloud-routers/requests/{circuit_id}/reject](https://api-beta.dev.packetfabric.net/openapi/index.html#/Cloud%20Router%20Third%20Party/cloud_router_request_reject)

### PR DESCRIPTION
**Pull request by pontovinte**
Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

## Description
Resource packetfabric_quick_connect_reject_request.

Closes #254 

## Checklist

- [x] tested locally
- [ ] added/updated acceptance tests
- [x] add examples (in example folder)
- [x] generate docs

### CODE REVIEW

**Comment by rjouhann** [comment]
Pending renaming `circuit_id` to `import_circuit_id`

**Comment by rjouhann** [comment]
1. the `optional` rejection_reason is [missing](https://api-beta.dev.packetfabric.net/openapi/index.html#/Cloud%20Router%20Third%20Party/cloud_router_request_reject)

```
{
  "rejection_reason": "Return filters are too broad."
}
```

2. just tested this resource and got this error:

```
packetfabric_quick_connect_reject_request.reject_request_quick_connect: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to packetfabric_quick_connect_reject_request.reject_request_quick_connect, provider
│ "provider[\"registry.terraform.io/packetfabric/packetfabric\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

Here is the payload when using the API to reject the request:
POST `/v2/services/cloud-routers/requests/PF-L3-IMP-2903116/reject`

Response:
```
{
    "message": "The Cloud Router Import Request has been rejected."
}
```

**Review by medzin — DISMISSED** [review]

**Review by caitlinwheeless — DISMISSED** [review]
Added template file and regenerated docs.

**Review by rjouhann — DISMISSED** [review]

**Review by medzin — APPROVED** [review]

**Review by rjouhann — DISMISSED** [review]
Confirm API renaming (rename `circuit_id` to `import_circuit_id`)

**Review by rjouhann — DISMISSED** [review]
Just renaming files to be consistent.

**Review by medzin — DISMISSED** [review]

**Pull request merged**
