### PR TITLE
Add zone to Cloud Router Connection and Prefixes to BGP Session data sources

### PR DESCRIPTION
**Pull request by Favouroked**
## Description
Add `zone`, `desired_nat`, `vlan` to cr connection response in `packetfabric_cloud_router_connections` data-source.
Add `prefixes` to create bgp response in `packetfabric_cloud_router_bgp_session` data-source.

## Cross-reference

PSE-10156 
PSE-10215

## Checklist

- [x] tested locally
- [x] added/updated acceptance tests
- [x] add examples (in example folder)
- [x] generate docs

[PSE-1234]: https://packetfabric.atlassian.net/browse/PSE-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PSE-10156]: https://packetfabric.atlassian.net/browse/PSE-10156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PSE-10215]: https://packetfabric.atlassian.net/browse/PSE-10215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by medzin — DISMISSED** [review]
lgtm

**Review by rjouhann — CHANGES_REQUESTED** [review]
I think the the prefixes attribute needs to be added. to the `internal/provider/datasource_bgp_session.go` similar to how to added the zone to the cloud router connection.

Then when you run tfdocsplugins, the bgp prefix should get added to the  `docs/packetfabric_cloud_router_bgp_session.md`.

**Comment by rjouhann** [comment]
@Favouroked do you also want to add those 2 new attributes in the CR connection response as we are at it?

- Add source VLAN to POST, GET packetfabric connctions endpoints - [PSE-10218]
- the Return user's nat choice_ as we are at it [PSE-10352]

**Comment by Favouroked** [comment]
sure

**Review by rjouhann — CHANGES_REQUESTED** [review]
@Favouroked I tested your branch locally in dev and I am not seeing 

1. **packetfabric_cloud_router_bgp_session**

The output shows:
`"prefixes" = toset([])`

while the API shows all the prefixes in my test:
```
        "prefixes": [
            {
                "prefix": "10.0.0.100/32",
                "match_type": "exact",
                "as_prepend": 1,
                "med": 10,
                "local_preference": 120,
                "bgp_prefix_uuid": "20dabd61-930d-49c0-8dc5-a905877e46ec",
                "type": "out",
                "order": 1
            },
            {
                "prefix": "10.0.0.1/32",
                "match_type": "exact",
                "as_prepend": 1,
                "med": 10,
                "local_preference": 120,
                "bgp_prefix_uuid": "aa7e37c9-70ff-4a94-9e90-8d16b6e4d52a",
                "type": "in",
                "order": 1
            }
        ],
```

2. **packetfabric_cloud_router_bgp_session**: zone

The output shows:

```
      "zone" = ""
```

while the API is showing
```
"zone": "W",
```

Thanks!
Romain

**Comment by rjouhann** [comment]
@Favouroked @medzin I did the following changes in this PR (also see latest commit):

1. `packetfabric_cloud_router_bgp_session`

- Added new function `flattenBgpSessionsPrefixes()` in `provider/datasource_bgp_session.go`. 
- Added `prefixes` to the `BgpSessionAssociatedResp`, `BgpSessionUpdate` and `BgpSessionAssociatedResp` struct in `packetfabric/bgp_session.go`
- Added missing `match_type`,  `as_prepend`, `med`, `local_preference` to `provider/datasource_bgp_prefixes.go`  and `provider/resource_bgp_session.go`
- Deleted `BgpSessionResponse` struct as it was the same as `BgpPrefix` struct (impacting both BGP data source and resources
- Added `circuit_id` and `connection_id` as required parameters to only show the BGP session related to a Cloud Router Connection

2. `packetfabric_cloud_router_connections ` 

- added in `flattenCloudConn()` in `provider/datasource_cloud_conn.go`
```
			flatten["zone"] = conn.Zone
			flatten["vlan"] = conn.Vlan
```

I tested the code locally and did not find any problem creating/updating/deleting a BGP session, showing BGP session details using the data source, and showing Cloud Router Connections using the data source.

**Review by rjouhann — APPROVED** [review]

**Review by medzin — APPROVED** [review]

**Pull request merged**
