### PR TITLE
IPSec and Google Cloud Router Connection impl.

### PR DESCRIPTION
**Pull request by pontovinte**
Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

### CODE REVIEW

**Comment by rjouhann** [comment]
Initial feedback:
1. Rename the resources to follow the name we gave for AWS Cloud Router (see comment inline the code). Should be `packetfabric_google_cloud_router_connection` and `packetfabric_ipsec_cloud_router_connection`
2. The `circuit_id` attribute is missing in the ``packetfabric_ipsec_cloud_router_connection``
```
│ Error: Unsupported argument
│ 
│   on main.tf line 205, in resource "packetfabric_cloud_router_ipsec_connection" "crc_2":
│  205:   circuit_id                   = packetfabric_cloud_router.cr.id
│ 
│ An argument named "circuit_id" is not expected here.
╵
```
3. The `pop` in both new resources should be a string, not a bool
```
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 155, in resource "packetfabric_cloud_router_google_connection" "crc_1":
│  155:   pop                         = var.pf_crc_pop1
│     ├────────────────
│     │ var.pf_crc_pop1 is "SEA3"
│ 
│ Inappropriate value for attribute "pop": a bool is required.
╵
```
4. Also `pop` in the google CRC resource should be required, not optional
5. `shared_key` is a required attribute not optional
6. As highlighted in the tech spec under API help > Cloud Router Connection IPsec, you can update the IPsec connection via this API PATCH [/v2/services/ipsec/{circuit_id}](https://docs.packetfabric.com/api/v2/redoc/#tag/IPsec/operation/ipsec_patch)
7. The 2 new data sources are missing in the provider
8. ``gateway_address`` is an IP address, not a UUID.
```
│ Error: expected "gateway_address" to be a valid UUID, got 127.0.0.1
│ 
│   with packetfabric_ipsec_cloud_router_connection.crc_2,
│   on main.tf line 216, in resource "packetfabric_ipsec_cloud_router_connection" "crc_2":
│  216:   gateway_address              = var.pf_crc_gateway_address
│ 
```
9. ``shared_key`` is a string, not a UUID.
```
│ Error: expected "shared_key" to be a valid UUID, got superCoolKey
│ 
│   with packetfabric_ipsec_cloud_router_connection.crc_2,
│   on main.tf line 217, in resource "packetfabric_ipsec_cloud_router_connection" "crc_2":
│  217:   shared_key                   = var.pf_crc_shared_key
│ 
╵
```
10. `cloud_settings` in the cloud router connection data source varies for each cloud providers as highlighted in the tech spec under API help > Cloud Router Connection AWS/Google/Azure/IBM/Oracle. ``internal/provider/datasource_cloud_conn_aws.go`` should be updated to reflect that
11. Something isn't working with the ``packetfabric_ipsec_cloud_router_connection`` resource at creation:
```
packetfabric_ipsec_cloud_router_connection.crc_2: Creating...
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to packetfabric_ipsec_cloud_router_connection.crc_2, provider
│ "provider[\"terraform.local/packetfabric/packetfabric\"]" produced an unexpected new value: Root resource was present, but
│ now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```
Example config I used:
```
resource "packetfabric_cloud_router" "cr" {
  provider     = packetfabric
  name         = "${var.tag_name}-${random_pet.name.id}"
  account_uuid = var.pf_account_uuid
  asn          = var.pf_cr_asn
  capacity     = var.pf_cr_capacity
  regions      = var.pf_cr_regions
}
resource "packetfabric_ipsec_cloud_router_connection" "crc_2" {
  provider                     = packetfabric
  description                  = "${var.tag_name}-${random_pet.name.id}-${var.pf_crc_pop2}"
  circuit_id                   = packetfabric_cloud_router.cr.id
  account_uuid                 = var.pf_account_uuid
  pop                          = var.pf_crc_pop2
  speed                        = var.pf_crc_speed
  ike_version                  = var.pf_crc_ike_version
  phase1_authentication_method = var.pf_crc_phase1_authentication_method
  phase1_group                 = var.pf_crc_phase1_group
  phase1_encryption_algo       = var.pf_crc_phase1_encryption_algo
  phase1_authentication_algo   = var.pf_crc_phase1_authentication_algo
  phase1_lifetime              = var.pf_crc_phase1_lifetime
  phase2_pfs_group             = var.pf_crc_phase2_pfs_group
  phase2_encryption_algo       = var.pf_crc_phase2_encryption_algo
  phase2_authentication_algo   = var.pf_crc_phase2_authentication_algo
  phase2_lifetime              = var.pf_crc_phase2_lifetime
  gateway_address              = var.pf_crc_gateway_address
  shared_key                   = var.pf_crc_shared_key
}
```
with the variables:
```
variable "pf_cr_asn" {
  type     = number
  default  = 4556 # PacketFabric ASN
  nullable = false
}
variable "pf_cr_capacity" {
  type    = string
  default = "1Gbps" # 100Mbps
}
variable "pf_cr_regions" {
  type    = list(string)
  default = ["US"] # ["UK"] ["US", "UK"]
}
variable "pf_crc_pop2" {
  type    = string
  default = "CHI1"
}
variable "pf_crc_ike_version" {
  type    = number
  default = 1
}
variable "pf_crc_phase1_authentication_method" {
  type    = string
  default = "pre-shared-key"
}
variable "pf_crc_phase1_group" {
  type    = string
  default = "group14"
}
variable "pf_crc_phase1_encryption_algo" {
  type    = string
  default = "aes-128-cbc"
}
variable "pf_crc_phase1_authentication_algo" {
  type    = string
  default = "sha1"
}
variable "pf_crc_phase1_lifetime" {
  type    = number
  default = 10800
}
variable "pf_crc_phase2_pfs_group" {
  type    = string
  default = "group14"
}
variable "pf_crc_phase2_encryption_algo" {
  type    = string
  default = "aes-128-cbc"
}
variable "pf_crc_phase2_authentication_algo" {
  type    = string
  default = "hmac-sha1-96"
}
variable "pf_crc_phase2_lifetime" {
  type    = number
  default = 28800
}
variable "pf_crc_gateway_address" {
  type    = string
  default = "76.191.25.20"
}
variable "pf_crc_shared_key" {
  type    = string
  default = "superCoolKey"
}
```

**Comment by rjouhann** [comment]
1. data source name `packetfabric_gcp_cloud_router_connection` should be `packetfabric_google_cloud_router_connection` same as the resource
2. same for `packetfabric_ipsec` data source should be `packetfabric_ipsec_cloud_router_connection`
3. we should not have `packetfabric_azr_cloud_router_connection` data source as this is for 0.3.1 (which will be name `packetfabric_azure_cloud_router_connection`)
4. `packetfabric_ipsec_connection_update` resource, I think we should call it `packetfabric_ipsec_cloud_router_connection_update` so we know by reading the name it is about cloud router and not something else

**Comment by rjouhann** [comment]
Feedback on the latest code as of Sept 28, 3pm PST:

1. `packetfabric_ipsec_cloud_router_connection_update` resource: the `customer_gateway_address` field is missing per  [API spec](https://docs.packetfabric.com/api/v2/swagger/#/IPsec/ipsec_patch)

To be consistent with ``packetfabric_ipsec_cloud_router_connection`` resource, could we also name `customer_gateway_address` as `gateway_address`?

2. Same with ``pre_shared_key`` (used in `packetfabric_ipsec_cloud_router_connection_update`) and ``shared_key`` (used in `packetfabric_ipsec_cloud_router_connection`).

3. There is a problem with the ``packetfabric_ipsec_cloud_router_connection`` resource. I think the API spec is missing
 ``"deleted": false,``

We may need to add in `cloud_router_connection.go` under `IPSecConnUpdate` and `IPSecConnUpdateResponse`:

``	Deleted                	   bool   `json:"deleted,omitempty"``

I will get the PF API schema updated and add the deleted bool in the response.

But there might be other problem. I will let you look into it.

**Error:**
```
2022-09-28T21:20:52.811Z [DEBUG] provider.terraform-provider-packetfabric: 
##[CLIENT | SEND_REQEST]## SENDING POST REQUEST: payload="map[account_uuid:24a0aef3-2784-48dc-9a8e-52d44d6da646 description:demo-pf-gcp-vpn-amused-bream-CHI1 gateway_address:117.109.121.202 ike_version:1 phase1_authentication_algo:sha1 phase1_authentication_method:pre-shared-key phase1_encryption_algo:aes-128-cbc phase1_group:group14 phase1_lifetime:10800 phase2_authentication_algo:hmac-sha1-96 phase2_encryption_algo:aes-128-cbc phase2_lifetime:28800 phase2_pfs_group:group14 pop:CHI1 shared_key:superCoolKey speed:100Mbps]" resp="map[account_uuid:24a0aef3-2784-48dc-9a8e-52d44d6da646 cloud_provider:map[] cloud_settings:map[] description:demo-pf-gcp-vpn-amused-bream-CHI1 pop:CHI1 speed:100Mbps time_created:2022-09-28T15:20:52.991463-0600 time_updated:2022-09-28T15:20:52.991463-0600]" tf_provider_addr=provider tf_req_id=03686530-56f0-6893-cb60-f478188349d6 tf_resource_type=packetfabric_ipsec_cloud_router_connection url=https://api.packetfabric.com/v2/services/cloud-routers/PF-L3-CUST-1747148/connections/ipsec @caller=/working/internal/packetfabric/client.go:150 @module=provider tf_rpc=ApplyResourceChange timestamp=2022-09-28T21:20:52.811Z
2022-09-28T21:20:58.167Z [ERROR] vertex "packetfabric_ipsec_cloud_router_connection.crc_2" error: Provider produced inconsistent result after apply
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to packetfabric_ipsec_cloud_router_connection.crc_2, provider
│ "provider[\"terraform.local/packetfabric/packetfabric\"]" produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
2022-09-28T21:20:58.192Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2022-09-28T21:20:58.196Z [DEBUG] provider: plugin process exited: path=.terraform/providers/terraform.local/packetfabric/packetfabric/0.0.1/linux_amd64/terraform-provider-packetfabric pid=995
2022-09-28T21:20:58.196Z [DEBUG] provider: plugin exited
```

API response to ``/v2/services/cloud-routers/{circuit_id}/connections/ipsec``:
```
{
    "circuit_id": "PF-IPSEC-1747180",
    "customer_gateway_address": "1.2.3.4",
    "local_gateway_address": "23.159.0.138",
    "ike_version": 1,
    "phase1_authentication_method": "pre-shared-key",
    "phase1_group": "group14",
    "phase1_encryption_algo": "aes-192-cbc",
    "phase1_authentication_algo": "sha-384",
    "phase1_lifetime": 10800,
    "phase2_pfs_group": "group14",
    "phase2_encryption_algo": "3des-cbc",
    "phase2_authentication_algo": "hmac-md5-96",
    "phase2_lifetime": 28800,
    "pre_shared_key": "superCoolKey",
    "deleted": false,
    "time_created": "2022-09-28T15:23:18.572770-0600",
    "time_updated": "2022-09-28T15:23:18.572770-0600",
    "vc_circuit_id": "PF-L3-CON-1747181",
    "description": "Test description",
    "account_uuid": "0d3b7d1f-9596-4d83-9f7f-b160f699784b",
    "pop": "DAL1",
    "speed": "100Mbps"
}
```

API response to ``/services/ipsec/{circuit_id}``:
```
{
    "circuit_id": "PF-IPSEC-1747189",
    "customer_gateway_address": "1.2.3.4",
    "local_gateway_address": "23.159.0.138",
    "ike_version": 1,
    "phase1_authentication_method": "pre-shared-key",
    "phase1_group": "group14",
    "phase1_encryption_algo": "aes-192-cbc",
    "phase1_authentication_algo": "sha-384",
    "phase1_lifetime": 10800,
    "phase2_pfs_group": "group14",
    "phase2_encryption_algo": "3des-cbc",
    "phase2_authentication_algo": "hmac-sha-256-128",
    "phase2_lifetime": 28800,
    "pre_shared_key": "superCoolKey",
    "deleted": false,
    "time_created": "2022-09-28T15:35:55.449826-0600",
    "time_updated": "2022-09-28T15:37:40.181757-0600"
}
```

**Comment by rjouhann** [comment]
We would like to rename the cloud router connection like this to be more coherent with the cloud service resource/datasource we have. @caitlinwheeless FYI as you will need to update your PR

Could we for 0.3 rename:
- `packetfabric_aws_cloud_router_connection` to `packetfabric_cloud_router_connection_aws`
- and for google and ipsec, it would become:
   - `packetfabric_cloud_router_connection_google`
   - `packetfabric_cloud_router_connection_ipsec`

**Comment by rjouhann** [comment]
Remaining 2 issues @pontovinte :

1. The ipsec cloud router still showing creating until it hit 10min timeout:

this is what I have in the status API:
```
{
    "circuit_id": "PF-L3-CON-1747318",
    "status": {
        "object": {
            "state": "bgp_not_created",
            "deleted": false
        },
        "current": {
            "state": "BGP_NOT_CREATED",
            "description": "bgp_not_created",
            "warning": false
        },
        "last_workflow": null
    }
}
```
2. there is also something wrong with the update:
```
[packetfabric_cloud_router.cr](http://packetfabric_cloud_router.cr/): Refreshing state... [id=PF-L3-CUST-1747315]
packetfabric_cloud_router_connection_ipsec.crc_2: Refreshing state... [id=PF-L3-CON-1747318]
packetfabric_cloud_router_bgp_session.crbs_2: Refreshing state... [id=56c63710-e2a6-4b2e-b8d7-7dff5a607f64]
packetfabric_cloud_router_bgp_prefixes.crbp_2: Refreshing state... [id=baf755c8-507e-41a6-9f9d-87433d93c200]
data.packetfabric_cloud_router_bgp_prefixes.bgp_prefix_crbp_2: Reading...
data.packetfabric_cloud_router_bgp_prefixes.bgp_prefix_crbp_2: Read complete after 1s [id=10d3058f-7af5-4a75-8993-df901ca04c2a]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place
Terraform will perform the following actions:
  # packetfabric_cloud_router_connection_ipsec.crc_2 will be updated in-place
  ~ resource "packetfabric_cloud_router_connection_ipsec" "crc_2" {
        id                           = "PF-L3-CON-1747318"
      ~ phase2_pfs_group             = "group15" -> "group14"
        # (16 unchanged attributes hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
Changes to Outputs:
  ~ packetfabric_bgp_prefix_crbp_2 = {
      ~ id                = "179ef927-6f19-4a73-afab-7874ac399018" -> "10d3058f-7af5-4a75-8993-df901ca04c2a"
        # (2 unchanged elements hidden)
    }
packetfabric_cloud_router_connection_ipsec.crc_2: Modifying... [id=PF-L3-CON-1747318]
╷
│ Error: Status: 404, body: {"message": "Cloud Router Connection PF-L3-CUST-1747315 not found", "request_id": "5d957494-8888-452b-ae01-95deec44494f"}
│ 
│   with packetfabric_cloud_router_connection_ipsec.crc_2,
│   on main.tf line 281, in resource "packetfabric_cloud_router_connection_ipsec" "crc_2":
│  281: resource "packetfabric_cloud_router_connection_ipsec" "crc_2" {
│
```
sounds like you are grabbing the ID of the CR instead of the CRC for the IPsec update/PATCH.

**Review by elXaptation — APPROVED** [review]

**Pull request merged**
