### PR TITLE
Fix/283: Fix context cancelled for Cloud Router Connection Read

### LINKED ISSUE #284: packetfabric_cloud_router - Intermittent 'Context Canceled' error on plan/apply
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform PacketFabric Provider Version

Terraform v1.1.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/packetfabric/packetfabric v0.4.2

### Affected Resource(s)

* packetfabric_cloud_router
* packetfabric_cloud_router_connection_google

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

**main.tf**
```hcl
terraform {
  required_providers {
    packetfabric = {
      source  = "PacketFabric/packetfabric"
      version = ">= 0.4.2"
    }
  }
}

provider "packetfabric" {
  host = "https://api.packetfabric.com"
  token = var.pf_api_key
  alias = "pf"
}

module "packetfabric-cloud-router" {
  source = "./modules/packetfabric"
  for_each = var.cloud_routers
  aws_account_id = var.aws_account_id
  pf_account_uuid = "redacted"
  name = each.key 
  asn = each.value.asn 
  capacity = each.value.capacity 
  regions = each.value.regions
  aws_connections = var.aws_connections[each.key]
  aws_bgp_sessions = var.aws_bgp_sessions[each.key]
  aws_inbound = var.aws_inbound[regex("\\w+-\\w+$", each.key)]
  aws_outbound = var.aws_outbound[regex("\\w+-\\w+$", each.key)]
  gcp_connections = var.gcp_connections[each.key]
  gcp_bgp_sessions = var.gcp_bgp_sessions[each.key]
  gcp_inbound = var.gcp_inbound[regex("\\w+-\\w+$", each.key)]
  gcp_outbound = var.gcp_outbound[regex("\\w+-\\w+$", each.key)]
  providers = {
    packetfabric = packetfabric.pf
  }
}
```

**modules/packetfabric/cr.tf**
```hcl
variable "pf_account_uuid" {
  type = string
}

variable "aws_account_id" {
  type = string
}

variable "asn" {
  type = number 
}

variable "name" {
  type = string
}

variable "capacity" {
  type = string
}

variable "regions" {
  type = list(string)
}

variable "aws_connections" {
  type = map(any)
}

variable "gcp_connections" {
  type = map(any)
}

variable "gcp_bgp_sessions" {
  type = map(any)
}

variable "aws_bgp_sessions" {
  type = map(any)
}

variable "gcp_inbound" {
  type = list(any)
}

variable "gcp_outbound" {
  type = list(any)
}

variable "aws_inbound" {
  type = list(any)
}

variable "aws_outbound" {
  type = list(any)
}

terraform {
  required_providers {
    packetfabric = {
      source  = "PacketFabric/packetfabric"
      version = ">= 0.4.2"
    }
  }
}

resource "packetfabric_cloud_router" "cr" {
  provider     = packetfabric
  account_uuid = var.pf_account_uuid
  asn          = var.asn
  name         = var.name
  capacity     = var.capacity
  regions      = var.regions
  timeouts {
    create = "20m"
  }
}

resource "packetfabric_cloud_router_connection_aws" "aws" {
  for_each = var.aws_connections
  provider = packetfabric
  account_uuid = var.pf_account_uuid
  aws_account_id = var.aws_account_id
  circuit_id = packetfabric_cloud_router.cr.id
  description = "aws-${each.key}"
  pop = each.value.pop
  speed = each.value.speed
  zone = each.value.zone
  timeouts {
    create = "20m"
  }
}

resource "packetfabric_cloud_router_connection_google" "gcp" {
  for_each = var.gcp_connections
  provider                    = packetfabric
  circuit_id                  = packetfabric_cloud_router.cr.id
  account_uuid                = var.pf_account_uuid
  google_pairing_key          = each.value.pairing_key
  google_vlan_attachment_name = each.value.vlan_attachment_name
  pop                         = each.value.pop
  speed                       = each.value.speed
  description                 = "gcp-${each.key}"
  timeouts {
    create = "20m"
  }
}


resource "packetfabric_cloud_router_bgp_session" "gcp" {
  for_each = var.gcp_bgp_sessions
  provider       = packetfabric
  circuit_id     = packetfabric_cloud_router.cr.id
  connection_id  = packetfabric_cloud_router_connection_google.gcp[each.key].id
  address_family = "v4"
  remote_asn     = each.value.asn
  remote_address = each.value.remote_address
  l3_address     = each.value.l3_address
  bfd_interval   = 1000
  bfd_multiplier = 5
  multihop_ttl   = 1
  disabled       = each.value.disabled

  dynamic "prefixes" {
    for_each   = { for i,v in var.gcp_inbound : i => v if contains(v.env, each.key)}
    content {
      prefix     = prefixes.value.prefix
      type       = "in"
      match_type = prefixes.value.match_type
      order      = prefixes.key
    }
  }

  dynamic "prefixes" {
    for_each   = { for i,v in var.gcp_outbound : i => v }
    content {
      prefix     = prefixes.value.prefix
      type       = "out"
      match_type = prefixes.value.match_type
      med        = lookup(prefixes.value, "med", 0)
      order      = prefixes.key
    }
  }
}


resource "packetfabric_cloud_router_bgp_session" "aws" {
  for_each = var.aws_bgp_sessions
  provider       = packetfabric
  circuit_id     = packetfabric_cloud_router.cr.id
  connection_id  = packetfabric_cloud_router_connection_aws.aws[each.key].id
  address_family = "v4"
  remote_asn     = each.value.asn
  remote_address = each.value.remote_address
  l3_address     = each.value.l3_address
  bfd_interval   = 300
  bfd_multiplier = 3
  multihop_ttl   = 1
  md5            = each.value.md5
  disabled       = each.value.disabled

  dynamic "prefixes" {
    for_each   = { for i,v in var.aws_inbound : i => v }
    content {
      prefix     = prefixes.value.prefix
      type       = "in"
      match_type = prefixes.value.match_type
      order      = prefixes.key
    }
  }

  dynamic "prefixes" {
    for_each   = { for i,v in var.aws_outbound : i => v }
    content {
      prefix     = prefixes.value.prefix
      type       = "out"
      match_type = prefixes.value.match_type
      order      = prefixes.key
    }
  }
}

```

**tfvars.json**
```json
{
    "aws_account_id": "redacted",
    "cloud_routers": {
        "dev-us-west": {
            "asn": 4556,
            "capacity": "100Gbps",
            "regions": ["US"]
        },
        "dev-us-east": {
            "asn": 4556,
            "capacity": "100Gbps",
            "regions": ["US"]
        }
    },
    "aws_connections": {
        "dev-us-west": {
            "dxg": {
                "speed": "50Mbps",
                "pop": "PDX2",
                "zone": "A"
            }
        },
        "dev-us-east": {
            "dxg": {
                "speed": "50Mbps",
                "pop": "WDC2",
                "zone": "E"
            }
        }
    },
    "gcp_connections": {
        "dev-us-west": {
            "dev": {
                "pairing_key": "redacted",
                "vlan_attachment_name": "vlan-dev-pf",
                "speed": "50Mbps",
                "pop": "SEA3"
            }
        },
        "dev-us-east": {
            "dev": {
                "pairing_key": "redacted",
                "vlan_attachment_name": "vlan-dev-pf",
                "speed": "50Mbps",
                "pop": "WDC1"
            }
        }
    },
    "gcp_bgp_sessions": {
        "dev-us-west": {
        },
        "dev-us-east": {
        }
    },
    "aws_bgp_sessions": {
        "dev-us-west": {
        },
        "dev-us-east": {
        }
    },
    "gcp_inbound": {
        "us-west": [
            { "prefix": "10.0.0.0/8", "match_type": "orlonger", "env": ["dev", "stage", "prod"] },
            { "prefix": "35.199.192.0/19", "match_type": "exact", "env": ["prod"] },
            { "prefix": "199.36.153.4/30", "match_type": "exact", "env": ["prod"] },
            { "prefix": "199.36.153.8/30", "match_type": "exact", "env": ["prod"] }
        ],
        "us-east": [
            { "prefix": "10.0.0.0/8", "match_type": "orlonger", "env": ["dev", "stage", "prod"] },
            { "prefix": "35.199.192.0/19", "match_type": "exact", "env": ["prod"] },
            { "prefix": "199.36.153.4/30", "match_type": "exact", "env": ["prod"] },
            { "prefix": "199.36.153.8/30", "match_type": "exact", "env": ["prod"] }
        ]
    },
    "gcp_outbound": {
        "us-west": [
            { "prefix": "1.1.1.1/32", "match_type": "exact" }
        ],
        "us-east": [
            { "prefix": "1.1.1.1/32", "match_type": "exact" }
        ]
    },
    "aws_inbound": {
        "us-west": [
            { "prefix": "10.0.0.0/8", "match_type": "orlonger" }
        ],
        "us-east": [
            { "prefix": "10.0.0.0/8", "match_type": "orlonger" }
        ]
    },
    "aws_outbound": {
        "us-west": [
            { "prefix": "1.1.1.1/32", "match_type": "exact" }
        ],
        "us-east": [
            { "prefix": "1.1.1.1/32", "match_type": "exact" }
        ]
    }
}
```
### Debug Output

https://gist.github.com/rparelius/53432d50911686438a071d0e0011d336

### Expected Behavior

Terraform should successfully generate a plan.

### Actual Behavior

terraform plan/apply errors out with `context canceled` error

### Steps to Reproduce

The resources must exist before it errors out during planning. Once created, if I try to destroy the resources, it errors out when executing the plan. 

```bash
terraform plan --var-file=tfvars.json
```

The error happens intermittently, just continue to `terraform plan` and it eventually happens. for me it happens about 25% of the time.

### PR DESCRIPTION
**Pull request by rjouhann**
## Description

Create a new context for each http call.
Remove 10sec delay (workaround for #177)

Closes #284

## Cross-reference

#177 
#165

## Checklist

- [x] tested locally

### CODE REVIEW

**Comment by rjouhann** [comment]
I actually wrote a little script to test this out.

```
#!/bin/bash

while true
do
    terraform plan --var-file=tfvars.json | tee -a logfile
    sleep 12
done
```

I can see the error doesn't happen that often but it does still happen so I don't think adding the 10sec timeout is the real solution but more a workaround. The request contexts are still getting "tangled up" somehow on the Terraform provider / Golang end.

**Comment by rjouhann** [comment]
Got again the `context canceled` error but this time with BGP session.

```
packetfabric_cloud_router_bgp_session.crbs_2: Destroying... [id=c0c61ba8-6872-460b-9937-286a8741ec47]
packetfabric_cloud_router_bgp_session.crbs_1: Destroying... [id=3f94b65e-4cd4-402a-aeac-0d05875afec2]
packetfabric_cloud_router_bgp_session.crbs_1: Destruction complete after 2s
╷
│ Error: Put "https://api.packetfabric.com/v2/services/cloud-routers/PF-L3-CUST-1754250/connections/PF-L3-CON-1754258/bgp": context canceled
│ 
│ 
╵
```

Added the 10sec delay. I still believe we are not fixing the root cause of the problem.

**Comment by rjouhann** [comment]
@elXaptation @pontovinte see suggestion https://github.com/PacketFabric/terraform-provider-packetfabric/issues/284#issuecomment-1338265340.

I don't think we should be adding a 10sec delay. We should probably revisit the fix we did for backbone VC context error https://github.com/PacketFabric/terraform-provider-packetfabric/issues/165.

**Comment by rjouhann** [comment]
@pontovinte @elXaptation I re-validated the scenario with the 16 Bakcbone VC (https://github.com/PacketFabric/terraform-provider-packetfabric/issues/165) using this change in the client.go instead of the 10sec delay and it works fine. Same for https://github.com/PacketFabric/terraform-provider-packetfabric/issues/284.

**Comment by pontovinte** [comment]
> @pontovinte @elXaptation I re-validated the scenario with the 16 Bakcbone VC (#165) using this change in the client.go instead of the 10sec delay and it works fine. Same for #284.

@rjouhann, that's good to read! But I'm worried if it won't cause any regression. Could you please test with other resources as well? Also test creating multiple resources simultaneously?

**Comment by rjouhann** [comment]
> @rjouhann, that's good to read! But I'm worried if it won't cause any regression. Could you please test with other resources as well? Also test creating multiple resources simultaneously?

@pontovinte  I tested it with a few resources (from the [use-cases ](https://github.com/PacketFabric/terraform-provider-packetfabric/tree/main/examples/use-cases)I created) and did not encounter problems. I think this makes sense to create a new context per HTTP request. Would a new context created for each HTTP call cause problems? Otherwise, do you have other suggestions otherwise to address the context error we are seeing when creating simultaneous resources?

**Review by pontovinte — APPROVED** [review]
Glad that @rjouhann was able to test with multiple resources, it shows it it didn't cause regression. But I would advice to watch this change in the next releases since we're replacing the Terraform's context that's being passed from resource and datasource down here.

**Pull request merged**
