### PR TITLE
Acceptance Tests v0.3.2

### PR DESCRIPTION
**Pull request by medzin**
This commit adds acceptance tests for the following resources:

 - packetfabric_port

 - packetfabric_ix_virtual_circuit_marketplace

 - packetfabric_point_to_point

 - packetfabric_backbone_virtual_circuit_marketplace

### CODE REVIEW

**Review by rjouhann — CHANGES_REQUESTED** [review]
I tried to execute the acceptance tests and got an error with the port being not available.

Maybe we should set the port config in env variable?

We have plans to add the `packetfabric_locations_port_availability` data source in v0.4.0 so we could use it to automatically select an available zone on a POP but this would be for later.

```
=== CONT  TestAccPort
    resource_port_test.go:48: Step 1/1 error: Error running apply: exit status 1
        
        Error: Status: 404, body: {"message": "No available 1Gbps LX port found in PHL1 zone B", "request_id": "f194c9a5-a90c-4ea4-b0f3-c3d75107b645"}
        
          with packetfabric_port.pf_25a104e5_7370_4ddc_b5e3_385ae3e4f00b,
          on terraform_plugin_test.tf line 2, in resource "packetfabric_port" "pf_25a104e5_7370_4ddc_b5e3_385ae3e4f00b":
           2: 	resource "packetfabric_port" "pf_25a104e5_7370_4ddc_b5e3_385ae3e4f00b" {
```

Also, could you document how to run the test in the README?

Essentially:
```
export PF_HOST="https://api.packetfabric.com"
export PF_TOKEN="api-secret"
export PF_ACCOUNT_UUID="1234"
export PF_ACC_TEST_ROUTING_ID="PD-WUY-9VB0" # PacketFabric Demo A
export PF_ACC_TEST_MARKET="HOU"
make testacc
```

**Comment by medzin** [comment]
Can we assume that we will use only 1Gbps ports for automatic testing? I can change the logic to only look for these ports.

**Comment by rjouhann** [comment]
> Can we assume that we will use only 1Gbps ports for automatic testing? I can change the logic to only look for these ports.

Yes, I think that makes sense as we are focusing on Terraform testing, not the port testing itself.

**Comment by medzin** [comment]
Ok, I updated the readme and changed the test pop search logic to always look for ports with specific speeds :)

**Review by rjouhann — CHANGES_REQUESTED** [review]
It seems there is still something wrong with the VC creation.

```
       Error: Missing required argument
        
          on terraform_plugin_test.tf line 23, in resource "packetfabric_backbone_virtual_circuit_marketplace" "pf_d5234141_8b04_4ea3_906e_771659ebb2ac":
          23: 		bandwidth {
        
        The argument "speed" is required, but no definition was found.
        
        Error: Missing required argument
        
          on terraform_plugin_test.tf line 23, in resource "packetfabric_backbone_virtual_circuit_marketplace" "pf_d5234141_8b04_4ea3_906e_771659ebb2ac":
          23: 		bandwidth {
        
        The argument "subscription_term" is required, but no definition was found.
--- FAIL: TestAccBackboneVirtualCircuitMarketplace (2.73s)
--- FAIL: TestAccIxVc (122.58s)
```

**Comment by medzin** [comment]
Probably the same issue as this one: https://github.com/PacketFabric/terraform-provider-packetfabric/issues/169

**Comment by rjouhann** [comment]
> Probably the same issue as this one: #169

Not the same problem but another problem. I know what to fix.

**Review by rjouhann — APPROVED** [review]
```
=== RUN   TestAccCloudRouter
=== PAUSE TestAccCloudRouter
=== RUN   TestAccIxVc
=== PAUSE TestAccIxVc
=== RUN   TestAccPointToPoint
=== PAUSE TestAccPointToPoint
=== RUN   TestAccPort
=== PAUSE TestAccPort
=== RUN   TestAccBackboneVirtualCircuitMarketplace
=== PAUSE TestAccBackboneVirtualCircuitMarketplace
=== CONT  TestAccCloudRouter
=== CONT  TestAccPort
--- PASS: TestAccCloudRouter (2.89s)
=== CONT  TestAccBackboneVirtualCircuitMarketplace
--- PASS: TestAccPort (132.90s)
=== CONT  TestAccPointToPoint
--- PASS: TestAccBackboneVirtualCircuitMarketplace (163.62s)
=== CONT  TestAccIxVc
--- PASS: TestAccIxVc (109.54s)
--- PASS: TestAccPointToPoint (258.14s)
PASS
ok      github.com/PacketFabric/terraform-provider-packetfabric/internal/provider       396.604s
```

**Pull request merged**
