### PR TITLE
209: Adding resource packetfabric_port_status

### LINKED ISSUE #209: resource packetfabric_port (enable/disable)
Update the existing resource `packetfabric_port` resource to enable/disable the port. 

2 attributes:
- `enabled` = true/false

API:
- POST [/v2/ports/{port_circuit_id}/enable](https://docs.packetfabric.com/api/v2/redoc/#tag/Ports/operation/enable_port) when enable set to true

- POST[ /v2/ports/{port_circuit_id}/disable](https://docs.packetfabric.com/api/v2/redoc/#tag/Ports/operation/disable_port) when enable set to false

Checklist:
- [ ] tested locally
- [ ] added/updated acceptance tests
- [ ] add examples (in example folder)
- [ ] generate docs

### PR DESCRIPTION
**Pull request by pontovinte**
Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

## Description

Updating resource packetfabric_port to add enable/disable capability.

Closes #209 

## Checklist

- [x] tested locally
- [ ] added/updated acceptance tests
- [x] add examples (in example folder)
- [x] generate docs

### CODE REVIEW

**Comment by rjouhann** [comment]
@pontovinte works great. However, it takes about 2-3 minutes for the port state to change from down/up.

Could we check the admin_status of the port after we disable/enable it?

**Port enable**
```
{
  ...
  admin_status          = "up"
  disabled              = false
  ...
  port_circuit_id       = "PF-AP-WDC1-1726464"
  time_created          = "2022-03-11T10:16:42.929389-0700"
  time_updated          = "2022-09-22T18:55:27.448174-0600"
  vc_mode               = "evpl"
  zone                  = "G"
}
```


**Port disable**
```
{
  ...
  admin_status          = "down"
  disabled              = true
  ...
  port_circuit_id       = "PF-AP-WDC1-1726464"
  time_created          = "2022-03-11T10:16:42.929389-0700"
  time_updated          = "2022-09-22T18:55:27.448174-0600"
  vc_mode               = "evpl"
  zone                  = "G"
}
```

**Comment by rjouhann** [comment]
@pontovinte 

I tried the latest changes and it looks like we should look after the `admin_status` **up/down** instead of `disabled`.
As you can see below, after the port is disabled, it shows `disable=true `but still show `admin_status=up` for a little while.

Could we update the status check looking at `admin_status` up/down?

```
packetfabric_port_disable.disable_port_2: Creating...
data.packetfabric_port.ports_all: Reading...
data.packetfabric_port.ports_all: Read complete after 0s [id=41cd52a7-ab38-492c-9364-0e2bd83693d0]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

packetfabric_port_2_full_details = toset([
  {
    "account_uuid" = "24a0aef3-2784-48dc-9a8e-52d44d6da646"
    "admin_status" = "up"
    "autoneg" = true
    "customer_name" = "PacketFabric DEMO B"
    "customer_uuid" = "172ccf44-fea5-4121-9816-2d0e60d678b2"
    "description" = "demo-peaceful-killdeer"
    "disabled" = true
    "is_cloud" = false
    "is_lag" = false
    "is_lag_member" = false
    "is_nni" = false
    "is_ptp" = false
    "lag_interval" = ""
    "market" = "WDC"
    "market_description" = "Washington DC"
    "media" = "LX"
    "member_count" = 0
    "mtu" = 9096
    "operational_status" = "down"
    "parent_lag_circuit_id" = ""
    "pop" = "WDC1"
    "port_circuit_id" = "PF-AP-WDC1-1754160"
    "region" = "US"
    "site" = "Equinix DC5"
    "site_code" = "EQ-DC5"
    "speed" = "1Gbps"
    "state" = "active"
    "status" = "provisioning"
    "subscription_term" = 1
    "time_created" = "2022-12-01T23:56:49.583451-0700"
    "time_updated" = "2022-12-02T00:15:51.272292-0700"
    "vc_mode" = ""
    "zone" = "E"
  },
])
```

**Review by elXaptation — APPROVED** [review]

**Comment by medzin** [comment]
Working on acceptance test :)

**Comment by medzin** [comment]
@rjouhann, how will the user check if the port is disabled?

**Comment by pontovinte** [comment]
> @pontovinte
> 
> I tried the latest changes and it looks like we should look after the `admin_status` **up/down** instead of `disabled`. As you can see below, after the port is disabled, it shows `disable=true `but still show `admin_status=up` for a little while.
> 
> Could we update the status check looking at `admin_status` up/down?
> 
> ```
> packetfabric_port_disable.disable_port_2: Creating...
> data.packetfabric_port.ports_all: Reading...
> data.packetfabric_port.ports_all: Read complete after 0s [id=41cd52a7-ab38-492c-9364-0e2bd83693d0]
> 
> Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
> 
> Outputs:
> 
> packetfabric_port_2_full_details = toset([
>   {
>     "account_uuid" = "24a0aef3-2784-48dc-9a8e-52d44d6da646"
>     "admin_status" = "up"
>     "autoneg" = true
>     "customer_name" = "PacketFabric DEMO B"
>     "customer_uuid" = "172ccf44-fea5-4121-9816-2d0e60d678b2"
>     "description" = "demo-peaceful-killdeer"
>     "disabled" = true
>     "is_cloud" = false
>     "is_lag" = false
>     "is_lag_member" = false
>     "is_nni" = false
>     "is_ptp" = false
>     "lag_interval" = ""
>     "market" = "WDC"
>     "market_description" = "Washington DC"
>     "media" = "LX"
>     "member_count" = 0
>     "mtu" = 9096
>     "operational_status" = "down"
>     "parent_lag_circuit_id" = ""
>     "pop" = "WDC1"
>     "port_circuit_id" = "PF-AP-WDC1-1754160"
>     "region" = "US"
>     "site" = "Equinix DC5"
>     "site_code" = "EQ-DC5"
>     "speed" = "1Gbps"
>     "state" = "active"
>     "status" = "provisioning"
>     "subscription_term" = 1
>     "time_created" = "2022-12-01T23:56:49.583451-0700"
>     "time_updated" = "2022-12-02T00:15:51.272292-0700"
>     "vc_mode" = ""
>     "zone" = "E"
>   },
> ])
> ```

@rjouhann, I notice that the API doesn't always send the `disabled` flag as part of the payload and for some reason it got on an infinite loop when checking for `admin_status`, I'm not sure if it's something related to the response returned from API. But I'm using the service status to verify if the request got completed wherever if it's to `disable/enable` and it works fine.

**Comment by pontovinte** [comment]
> @rjouhann, how will the user check if the port is disabled?

@rjouhann may have more details, since he's the PF expert here, but I believe the user can use the datasource `packetfabric_port`.

**Comment by rjouhann** [comment]
> > @rjouhann, how will the user check if the port is disabled?
> 
> @rjouhann may have more details, since he's the PF expert here, but I believe the user can use the datasource `packetfabric_port`.

As discussed in Slack, let's have `packetfabric_port_status`  resource instead of  `packetfabric_port_disable` resource to manage port status with an `enabled` boolean attribute (default to true). @pontovinte could you make the necessary changes?

**Review by caitlinwheeless — APPROVED** [review]
Description looks fine!

**Review by rjouhann — APPROVED** [review]

**Pull request merged**
