### PR TITLE
Fix/157: Add a 20sec delay when deleting a Cloud Router Connection

### PR DESCRIPTION
**Pull request by pontovinte**
Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

### CODE REVIEW

**Review by rjouhann — CHANGES_REQUESTED** [review]
It seems the test is failing now with this change (check under the Checks tab)

```
go test '-timeout=30s' '-parallel=4' github.com/PacketFabric/terraform-provider-packetfabric github.com/PacketFabric/terraform-provider-packetfabric/internal/packetfabric github.com/PacketFabric/terraform-provider-packetfabric/internal/provider github.com/PacketFabric/terraform-provider-packetfabric/internal/testutil 
?   	github.com/PacketFabric/terraform-provider-packetfabric	[no test files]
panic: test timed out after 30s
```

**Comment by pontovinte** [comment]
I decreased the timeout from 30s to 20s. The tests are using 30s as timeout.

**Review by rjouhann — CHANGES_REQUESTED** [review]
@pontovinte  I see you made the changes only for AWS Cloud Router Connection. Could you also add this change to other Cloud Router Connections? (Google, Azure, IBM, Oracle, Port, IPsec).

**Comment by pontovinte** [comment]
@rjouhann, sure, do you mind sharing the resources names where this delay must be applied as well? I want to avoid adding it on the wrong place.

**Comment by rjouhann** [comment]
> @rjouhann, sure, do you mind sharing the resources names where this delay must be applied as well? I want to avoid adding it on the wrong place.

- [] packetfabric_cloud_router_connection_aws
- [ ] packetfabric_cloud_router_connection_google
- [ ] packetfabric_cloud_router_connection_azure
- [ ] packetfabric_cloud_router_connection_ibm
- [ ] packetfabric_cloud_router_connection_oracle
- [ ] packetfabric_cloud_router_connection_ipsec
- [ ] packetfabric_cloud_router_connection_port

**Review by rjouhann — APPROVED** [review]

**Pull request merged**
