### PR TITLE
Update untagged, fix warning and cleanup

### PR DESCRIPTION
**Pull request by rjouhann**
## Description

- Remove `omitempty` in schema for `untagged` in `packetfabric_backbone_virtual_circuit`
- Fix following warning: 
  .flex_bandwidth_id: planned value cty.StringVal("") for a non-computed attribute
- Cleanup redundant functions `extractIXVcInterface()` = `extractBackboneInterface()` and `ixVcSpeedOptions` = `speedOptions()`
- Add link about VLAN tagging rules in the docs for backbone VC

## Checklist

- [x] tested locally
- [x] added/updated docs

### CODE REVIEW

**Comment by medzin** [comment]
It may be reasonable to update terraform SDK and check if the bug persists, and if so, then report it to Hashicorp.

**Review by medzin — CHANGES_REQUESTED** [review]
The problem is with the `Untagged` field definition:

https://github.com/PacketFabric/terraform-provider-packetfabric/blob/main/internal/packetfabric/services.go#L36

We should remove `omitempty` or change the type to `*bool`.

**Comment by medzin** [comment]
@rjouhann see: https://go.dev/play/p/G7XMvAQICno

**Comment by rjouhann** [comment]
@medzin it works with your suggestion!!

```
request_params
{"rate_limit_in": 100, "rate_limit_out": 100, "description": "vc-romain-test", "interfaces": [{"port_circuit_id": "PF-AP-SFO1-1759269", "vlan": 733, "untagged": false}]}
```

**Review by medzin — APPROVED** [review]

**Pull request merged**
