### PR TITLE
#181: Don't set autoneg attribute if absent.

### PR DESCRIPTION
**Pull request by pontovinte**
Signed-off-by: Yrineu Rodrigues <yrineu@pontovinte.com>

### CODE REVIEW

**Review by rjouhann — CHANGES_REQUESTED** [review]
I am still facing the same error with latest code on that branch `fix/181`.

```
packetfabric_port.port_1a: Modifying... [id=PF-AP-DEN2-1749525]
2022-10-21T22:55:35.806Z [INFO]  Starting apply for packetfabric_port.port_1a
2022-10-21T22:55:35.807Z [DEBUG] packetfabric_port.port_1a: applying the planned Update change
2022-10-21T22:55:35.810Z [ERROR] provider.terraform-provider-packetfabric: Response contains error diagnostic: @caller=/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto tf_proto_version=5.3 tf_provider_addr=provider tf_req_id=87da70cb-110a-5feb-7105-6181fa805dc9 tf_rpc=ApplyResourceChange diagnostic_detail= diagnostic_severity=ERROR diagnostic_summary="autoneg is a required field" tf_resource_type=packetfabric_port timestamp=2022-10-21T22:55:35.810Z
2022-10-21T22:55:35.816Z [ERROR] vertex "packetfabric_port.port_1a" error: autoneg is a required field
╷
│ Error: autoneg is a required field
│ 
│   with packetfabric_port.port_1a,
│   on main.tf line 23, in resource "packetfabric_port" "port_1a":
│   23: resource "packetfabric_port" "port_1a" {
│ 
╵
```

**Comment by rjouhann** [comment]
@pontovinte I just tested your last commit and I am hitting this error below. It looks like you are using the name instead of the port ID for the PATCH in the URL.

```
packetfabric_port.port_1a: Modifying... [id=PF-AP-DEN2-1749657]
2022-10-25T16:28:32.916Z [INFO]  Starting apply for packetfabric_port.port_1a
2022-10-25T16:28:32.917Z [DEBUG] packetfabric_port.port_1a: applying the planned Update change
2022-10-25T16:28:32.920Z [ERROR] provider.terraform-provider-packetfabric: Response contains error diagnostic: tf_resource_type=packetfabric_port tf_rpc=ApplyResourceChange @caller=/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto diagnostic_severity=ERROR tf_proto_version=5.3 tf_provider_addr=provider tf_req_id=949cafd2-20df-64d4-f0b0-fcccd505c931 diagnostic_detail= diagnostic_summary="Patch "https://api.packetfabric.com/v2/ports/demo-sterling-anchovy-a-test": context canceled" timestamp=2022-10-25T16:28:32.920Z
2022-10-25T16:28:32.928Z [ERROR] vertex "packetfabric_port.port_1a" error: Patch "https://api.packetfabric.com/v2/ports/demo-sterling-anchovy-a-test": context canceled
╷
│ Error: Patch "https://api.packetfabric.com/v2/ports/demo-sterling-anchovy-a-test": context canceled
│ 
│   with packetfabric_port.port_1a,
│   on main.tf line 23, in resource "packetfabric_port" "port_1a":
│   23: resource "packetfabric_port" "port_1a" {
│ 
╵
2022-10-25T16:28:32.953Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2022-10-25T16:28:32.956Z [DEBUG] provider: plugin process exited: path=.terraform/providers/terraform.local/packetfabric/packetfabric/0.0.1/linux_amd64/terraform-provider-packetfabric pid=421
2022-10-25T16:28:32.956Z [DEBUG] provider: plugin exited

```

**Comment by pontovinte** [comment]
That's strange, because I tested here and I got the `PortCircuitID` as explicited on the following code:

```
	if resp != nil {
		d.SetId(resp.PortCircuitID)
	}
```
So, I gonna send a new patch using the ID explicitly.

**Comment by pontovinte** [comment]
I found out that the issue happens only when update the description only, the parameters were inverted. I just sent a new patch with the fix. Thanks for catching that.

**Comment by rjouhann** [comment]
@pontovinte  still having problems when trying to update the description, the URL looks good though now, not sure why we get a context canceled error. Things seems to be fine when doing the PATCH directly with the API.

```
packetfabric_port.port_1a: Modifying... [id=PF-AP-DEN2-1749692]
2022-10-26T00:42:23.261Z [INFO]  Starting apply for packetfabric_port.port_1a
2022-10-26T00:42:23.261Z [DEBUG] packetfabric_port.port_1a: applying the planned Update change
2022-10-26T00:42:23.265Z [ERROR] provider.terraform-provider-packetfabric: Response contains error diagnostic: diagnostic_detail= diagnostic_summary="Patch "https://api.packetfabric.com/v2/ports/PF-AP-DEN2-1749692": context canceled" tf_proto_version=5.3 tf_req_id=3f64e22d-8dc9-f44e-ada2-a692201418f9 tf_resource_type=packetfabric_port tf_rpc=ApplyResourceChange @caller=/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto diagnostic_severity=ERROR tf_provider_addr=provider timestamp=2022-10-26T00:42:23.264Z
2022-10-26T00:42:23.269Z [ERROR] vertex "packetfabric_port.port_1a" error: Patch "https://api.packetfabric.com/v2/ports/PF-AP-DEN2-1749692": context canceled
╷
│ Error: Patch "https://api.packetfabric.com/v2/ports/PF-AP-DEN2-1749692": context canceled
│ 
│   with packetfabric_port.port_1a,
│   on main.tf line 23, in resource "packetfabric_port" "port_1a":
│   23: resource "packetfabric_port" "port_1a" {
│ 
╵
```

See details when doing the change directly using the API
```
Request URL: https://api.packetfabric.com/v2/ports/PF-AP-DEN2-1749692
Request Method: PATCH
Status Code: 200 
{"description":"demo-exciting-buffalo-a-test"}
```

**Review by rjouhann — CHANGES_REQUESTED** [review]
@pontovinte  still having problems when trying to update the description, the URL looks good though now, not sure why we get a context canceled error. Things seems to be fine when doing the PATCH directly with the API.

```
packetfabric_port.port_1a: Modifying... [id=PF-AP-DEN2-1749692]
2022-10-26T00:42:23.261Z [INFO]  Starting apply for packetfabric_port.port_1a
2022-10-26T00:42:23.261Z [DEBUG] packetfabric_port.port_1a: applying the planned Update change
2022-10-26T00:42:23.265Z [ERROR] provider.terraform-provider-packetfabric: Response contains error diagnostic: diagnostic_detail= diagnostic_summary="Patch "https://api.packetfabric.com/v2/ports/PF-AP-DEN2-1749692": context canceled" tf_proto_version=5.3 tf_req_id=3f64e22d-8dc9-f44e-ada2-a692201418f9 tf_resource_type=packetfabric_port tf_rpc=ApplyResourceChange @caller=/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto diagnostic_severity=ERROR tf_provider_addr=provider timestamp=2022-10-26T00:42:23.264Z
2022-10-26T00:42:23.269Z [ERROR] vertex "packetfabric_port.port_1a" error: Patch "https://api.packetfabric.com/v2/ports/PF-AP-DEN2-1749692": context canceled
╷
│ Error: Patch "https://api.packetfabric.com/v2/ports/PF-AP-DEN2-1749692": context canceled
│ 
│   with packetfabric_port.port_1a,
│   on main.tf line 23, in resource "packetfabric_port" "port_1a":
│   23: resource "packetfabric_port" "port_1a" {
│ 
╵
```

See details when doing the change directly using the API
```
Request URL: https://api.packetfabric.com/v2/ports/PF-AP-DEN2-1749692
Request Method: PATCH
Status Code: 200 
{"description":"demo-exciting-buffalo-a-test"}
```

**Pull request merged**
